const DUPLICATE_USERNAME = 'DUPLICATE_USERNAME';
const INVALID_USERNAME = 'INVALID_USERNAME';
const INVALID_USER_ID = 'INVALID_USER_ID';
const UNAUTHORIZED = 'UNAUTHORIZED';

const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL';
const INVALID_EMAIL = 'INVALID_EMAIL';
const INVALID_EMAIL_VERIFICATION_ID = 'INVALID_EMAIL_VERIFICATION_ID';
const INVALID_EMAIL_VERIFICATION_TOKEN = 'INVALID_EMAIL_VERIFICATION_TOKEN';
const EMAIL_VERIFICATION_TOKEN_EXPIRED = 'EMAIL_VERIFICATION_TOKEN_EXPIRED';

const DUPLICATE_PHONE_NUMBER = 'DUPLICATE_PHONE_NUMBER';
const INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER';
const INVALID_PHONE_NUMBER_VERIFICATION_TOKEN =
  'INVALID_PHONE_NUMBER_VERIFICATION_TOKEN';
const INCORRECT_OTP = 'INCORRECT_OTP';

const INVALID_PASSWORD = 'INVALID_PASSWORD';
const PASSWORDS_MISMATCH = 'PASSWORDS_MISMATCH';
const INCORRECT_PASSWORD = 'INCORRECT_PASSWORD';

const INVALID_OAUTH_PROVIDER = 'INVALID_OAUTH_PROVIDER';
const INVALID_OAUTH_STATE = 'INVALID_OAUTH_STATE';

const UNKNOWN_ERROR = 'UNKNOWN_ERROR'; // only for development while other error types are not yet handled

module.exports = {
  DUPLICATE_USERNAME,
  DUPLICATE_EMAIL,
  INVALID_EMAIL,
  INVALID_PASSWORD,
  PASSWORDS_MISMATCH,
  INVALID_EMAIL_VERIFICATION_TOKEN,
  UNKNOWN_ERROR,
  EMAIL_VERIFICATION_TOKEN_EXPIRED,
  DUPLICATE_PHONE_NUMBER,
  INVALID_PHONE_NUMBER,
  INVALID_PHONE_NUMBER_VERIFICATION_TOKEN,
  INCORRECT_PASSWORD,
  INCORRECT_OTP,
  INVALID_USER_ID,
  INVALID_EMAIL_VERIFICATION_ID,
  UNAUTHORIZED,
  INVALID_USERNAME,
  INVALID_OAUTH_PROVIDER,
  INVALID_OAUTH_STATE,
};
